services:
  nginx:
    build: ./nginx/.
    ports:
      - 443:443
    networks:
      - nginx-word
    volumes:
      - ${HOST_PATH_NGINX}:${WP_VOLUME}
    env_file:
      - ./.env
  mariadb:
    build: ./mariadb/.
    ports: 
      - 3306:3306
    networks:
      - word-db
    env_file:
      - ./.env
    volumes:
      - ${HOST_PATH_DB}:${MDB_VOLUME}
  wordpress:
    build: ./wordpress/.
    ports:
      - 9000:9000
    networks :
      - nginx-word
      - word-db
    env_file:
      - ./.env
    volumes:
      - $HOST_PATH_NGINX:$WP_VOLUME
networks:
  word-db:
  nginx-word:


  
